spring:
    application:
        name: client_spring
    datasource:
        url: jdbc:mysql://localhost:3306/fastsns
        username: root
        password: { { db_password } }
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: create
        show-sql: true

    data:
        redis:
            host: 127.0.0.1
            port: 6379
    session:
        redis:
            flush-mode: on_save